messages:
  notwhitelisted: 'Поддерживаются только подтверждённые чаты.'
  error: 'Произошла неизвестная ошибка. Оповестите DasGortyCH.'
discord: [] # add here discord channel's ids
telegram: [] # add here telegram chat's ids
